### ISSUE TITLE
Wrong URL for paper "Geometric Pose Affordance: 3D Human Pose with Scene Constraints"

### ISSUE THREAD

**Issue by HBadertscher** [wangzheallen/awesome-human-pose-estimation#8]
Hi, first of all thanks for sharing this nice list.

In the section "3d-pose-estimation", the last entry:

> Geometric Pose Affordance: 3D Human Pose with Scene Constraints - Zhe Wang, Liyan Chen, Shaurya Rathore, Daeyun Shin, Charless Fowlkes (Arxiv 2019)"

has a wrong URL: it points to [https://arxiv.org/abs/1907.10045](https://arxiv.org/abs/1907.10045) instead of [https://arxiv.org/abs/1905.07718](https://arxiv.org/abs/1905.07718)

**Comment by wangzheallen** [comment]
Thanks for pointing out :)
